import { LabelElement } from "@/types/canvas";

export interface QuickTemplate {
  id: string;
  name: string;
  description: string;
  elements: Partial<LabelElement>[];
}

export const QUICK_TEMPLATES: QuickTemplate[] = [
  {
    id: "product-label",
    name: "Ürün Etiketi",
    description: "İsim, Barkod ve QR Kod içeren standart ürün etiketi.",
    elements: [
      {
        type: "text",
        content: "ÜRÜN ADI BURAYA",
        xMm: 5,
        yMm: 5,
        widthMm: 40,
        heightMm: 8,
        fontSizePt: 14,
        fontWeight: "bold",
        font: "Inter",
      },
      {
        type: "barcode",
        content: "123456789012",
        xMm: 5,
        yMm: 15,
        widthMm: 40,
        heightMm: 15,
        barcodeType: "CODE128",
      },
      {
        type: "qr",
        content: "https://example.com",
        xMm: 50,
        yMm: 5,
        widthMm: 25,
        heightMm: 25,
      },
    ],
  },
  {
    id: "price-tag",
    name: "Fiyat Etiketi",
    description: "Büyük fiyat ve para birimi sembolü.",
    elements: [
      {
        type: "text",
        content: "149.90",
        xMm: 5,
        yMm: 5,
        widthMm: 30,
        heightMm: 15,
        fontSizePt: 28,
        fontWeight: "bold",
        textAlign: "right",
      },
      {
        type: "text",
        content: "TL",
        xMm: 36,
        yMm: 10,
        widthMm: 10,
        heightMm: 8,
        fontSizePt: 14,
        fontWeight: "bold",
      },
      {
        type: "rect",
        xMm: 2,
        yMm: 2,
        widthMm: 46,
        heightMm: 21,
        fill: "transparent",
        stroke: "#000000",
        strokeWidthMm: 0.5,
      },
    ],
  },
  {
    id: "shipping-label",
    name: "Adres / Kargo",
    description: "Gönderici ve alıcı blokları.",
    elements: [
      {
        type: "text",
        content: "GÖNDERİCİ:",
        xMm: 5,
        yMm: 5,
        widthMm: 30,
        heightMm: 5,
        fontSizePt: 10,
        fontWeight: "bold",
      },
      {
        type: "text",
        content: "Ad Soyad / Firma Adı\nAdres Satırı 1\nŞehir / Ülke",
        xMm: 5,
        yMm: 10,
        widthMm: 50,
        heightMm: 15,
        fontSizePt: 9,
      },
      {
        type: "line",
        xMm: 5,
        yMm: 30,
        widthMm: 50,
        heightMm: 1,
        lineDirection: "horizontal",
        stroke: "#cccccc",
        strokeWidthMm: 0.2,
      },
      {
        type: "text",
        content: "ALICI:",
        xMm: 5,
        yMm: 35,
        widthMm: 30,
        heightMm: 5,
        fontSizePt: 10,
        fontWeight: "bold",
      },
      {
        type: "text",
        content: "Alıcı Ad Soyad\nTeslimat Adresi Detayı\nİlçe / İl",
        xMm: 5,
        yMm: 40,
        widthMm: 50,
        heightMm: 15,
        fontSizePt: 9,
      },
    ],
  },
  {
    id: "data-table",
    name: "Bilgi Tablosu",
    description: "Anahtar-değer çiftlerinden oluşan teknik bilgi tablosu.",
    elements: [
      { type: "text", content: "Model:", xMm: 5, yMm: 5, fontSizePt: 9, fontWeight: "bold" },
      { type: "text", content: "SN-98234", xMm: 25, yMm: 5, fontSizePt: 9 },
      { type: "line", xMm: 5, yMm: 10, widthMm: 50, stroke: "#eee", strokeWidthMm: 0.1 },
      { type: "text", content: "Üretim:", xMm: 5, yMm: 12, fontSizePt: 9, fontWeight: "bold" },
      { type: "text", content: "04/2026", xMm: 25, yMm: 12, fontSizePt: 9 },
      { type: "line", xMm: 5, yMm: 17, widthMm: 50, stroke: "#eee", strokeWidthMm: 0.1 },
      { type: "text", content: "Menşei:", xMm: 5, yMm: 19, fontSizePt: 9, fontWeight: "bold" },
      { type: "text", content: "Türkiye", xMm: 25, yMm: 19, fontSizePt: 9 },
    ],
  },
  {
    id: "sale-badge",
    name: "İndirim Rozeti",
    description: "Dikkat çekici indirim veya kampanya rozeti.",
    elements: [
      { type: "ellipse", xMm: 5, yMm: 5, widthMm: 20, heightMm: 20, fill: "#ff4444" },
      { type: "text", content: "SALE", xMm: 7, yMm: 8, fontSizePt: 10, fontWeight: "bold", fill: "white", textAlign: "center", widthMm: 16 },
      { type: "text", content: "%50", xMm: 7, yMm: 13, fontSizePt: 12, fontWeight: "bold", fill: "white", textAlign: "center", widthMm: 16 },
    ],
  },
  {
    id: "nutrition-fact",
    name: "Besin Değerleri",
    description: "Gıda etiketleri için temel besin değerleri tablosu.",
    elements: [
      { type: "text", content: "Besin Enerjisi / Nutrition Facts", xMm: 2, yMm: 2, fontSizePt: 8, fontWeight: "bold", widthMm: 46 },
      { type: "line", xMm: 2, yMm: 6, widthMm: 46, stroke: "#000", strokeWidthMm: 0.4 },
      { type: "text", content: "Enerji (kcal)", xMm: 2, yMm: 8, fontSizePt: 7 },
      { type: "text", content: "450", xMm: 40, yMm: 8, fontSizePt: 7, fontWeight: "bold", textAlign: "right" },
      { type: "line", xMm: 2, yMm: 11, widthMm: 46, stroke: "#ccc", strokeWidthMm: 0.1 },
      { type: "text", content: "Yağ (g)", xMm: 2, yMm: 13, fontSizePt: 7 },
      { type: "text", content: "12", xMm: 40, yMm: 13, fontSizePt: 7, fontWeight: "bold", textAlign: "right" },
      { type: "line", xMm: 2, yMm: 16, widthMm: 46, stroke: "#ccc", strokeWidthMm: 0.1 },
      { type: "text", content: "Karşılanan Günlük Değer (%)", xMm: 2, yMm: 18, fontSizePt: 6 },
    ],
  },
];
